_target_: paper_src.models.LatentSAEv2
input_size: 10
encoder_size: 64
latent_size: 3
dynamics:
  _target_: paper_src.models.RNN
  cell:
    _target_: torch.nn.GRUCell
    input_size: 1
    hidden_size: ${model.latent_size}
dropout: 0.05
learning_rate: 1.0e-3
weight_decay: 1.0e-4
